apiVersion: v1
kind: Pod
metadata:
  name: exemplo-pod
spec:
  containers:
    - name: app
      image: nginx:latest
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
        requests:
          memory: "128Mi"
          cpu: "250m"
      volumeMounts:
        - name: dados
          mountPath: /data
  volumes:
    - name: dados
      emptyDir: {}